<?php
/**
 * User: liyu
 * Date: 2018/8/9
 * Time: 16:36
 * Desc: ReceiveConfirmEvent.php
 */

namespace ddd\Profit\Domain\Model\Payment;


use ddd\Common\Domain\BaseEvent;

class PayClaimEvent extends BaseEvent
{
    public function initEventName() {
        parent::initEventName(); // TODO: Change the autogenerated stub
        $this->eventName='合同后补认领付款成功';
    }
}