<?php
/**
 * User: liyu
 * Date: 2018/8/9
 * Time: 16:36
 * Desc: ReceiveConfirmEvent.php
 */

namespace ddd\Profit\Domain\Model\Invoice;


use ddd\Common\Domain\BaseEvent;

class InputInvoiceCheckPassEvent extends BaseEvent
{
    public function initEventName() {
        parent::initEventName(); // TODO: Change the autogenerated stub
        $this->eventName = '合同进项票审核通过';
    }
}