<?php

/**
 * Desc:
 * User: susiehuang
 * Date: 2018/3/16 0016
 * Time: 9:51
 */

namespace ddd\domain\entity\project;

use ddd\Common\Domain\BaseEntity;
use ddd\Common\IAggregateRoot;
use ddd\domain\entity\contract\Contract;
use ddd\domain\event\project\ProjectRejectEvent;
use ddd\domain\event\project\ProjectSubmitEvent;
use ddd\domain\event\subscribe\EventSubscribeService;
use ddd\domain\iRepository\project\IProjectRepository;
use ddd\domain\tRepository\project\ProjectRepository;
use ddd\infrastructure\Utility;

class Project extends BaseEntity implements IAggregateRoot
{
    use ProjectRepository;
    
    #region Event

    /**
     * 项目提交事件
     */
    const EVENT_AFTER_SUBMIT="onAfterSubmit";

    /**
     * 驳回事件
     */
    const EVENT_AFTER_REJECT="onAfterReject";

    /**
     * 合同完结事件
     */
    const EVENT_AFTER_DONE="onAfterDone";

    #endregion

    #region public property

    /**
     * project_id
     * @var      bigint
     */
    public $project_id;

    /**
     * 交易主体
     * @var      int
     */
    public $corporation_id;

    /**
     * 项目编号
     * @var      string
     */
    public $project_code;

    /**
     * 项目类型
     * @var      int
     */
    public $type;

    /**
     * 项目名称
     * @var      string
     */
    public $project_name;

    /**
     * 项目负责人
     * @var      int
     */
    public $manager_user_id;

    /**
     * 是否可以退回
     * @var      int
     */
    public $is_can_back=1;

    /**
     * 状态
     * @var      int
     */
    public $status;

    /**
     * 状态时间
     * @var      int
     */
    public $status_time;

    /**
     * 开始日期
     * @var      date
     */
    public $start_date;

    /**
     * 截止日期
     * @var      date
     */
    public $end_date;

    /**
     * 说明
     * @var      string
     */
    public $remark;

    /**
     * 项目概况
     * @var      ProjectDetail
     */
    public $detail;

    #endregion

    /**
     * @var IProjectRepository
     */
    //protected $repository;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function getId()
    {
        return $this->project_id;
    }

    function getIdName()
    {
        return "project_id";
    }

    function setId($value)
    {
        return $this->project_id=$value;
    }


    /**
     * 获取仓储
     * @return IProjectRepository|object
     * @throws \Exception
     */
    /*protected function getRepository()
    {
        if (empty($this->repository))
        {
            $this->repository=DIService::getRepository(IProjectRepository::class);
        }
        return $this->repository;
    }*/

    /**
     * Project
     * @param null $params
     * @return Project
     * @throws \Exception
     */
    public static function create($params=null)
    {
        return new Project($params);
    }

    /**
     * 驳回
     * @throws \Exception
     */
    public function rejectAndSave()
    {
        // TODO: implement
        $this->status=\Project::STATUS_BACK;
        $this->status_time=Utility::getNow();
        $this->getProjectRepository()->reject($this);

        $this->afterReject();
    }

    /**
     * @throws \Exception
     */
    protected function afterReject()
    {
        EventSubscribeService::bind($this,static::EVENT_AFTER_REJECT,EventSubscribeService::ProjectRejectEvent);
        if($this->hasEventHandler(static::EVENT_AFTER_REJECT))
            $this->onAfterSubmit(new ProjectRejectEvent($this));
    }

    /**
     * 作废
     * @throws \Exception
     */
    public function trashAndSave()
    {
        // TODO: implement
        $this->status=\Project::STATUS_STOP;
        $this->status_time=Utility::getNow();
        $this->getProjectRepository()->trash($this);
    }

    /**
     * 是否可以提交
     * @return bool
     */
    public function isCanSubmit()
    {
        return $this->status>\Project::STATUS_STOP && $this->status<\Project::STATUS_SUBMIT;
    }

    /**
     * 提交
     * @throws \Exception
     */
    public function submit()
    {
        // TODO: implement
        $this->status=ProjectStatus::SUBMIT;
        $this->status_time=Utility::getNow();

        $this->afterSubmit();
    }

    /**
     * 提交且保存到持久化
     * @throws \Exception
     */
    public function submitAndSave()
    {
        // TODO: implement
        $this->submit();
        $this->getProjectRepository()->submit($this);
    }

    /**
     * @throws \Exception
     */
    protected function afterSubmit()
    {
        EventSubscribeService::bind($this,static::EVENT_AFTER_SUBMIT,EventSubscribeService::ProjectSubmitEvent);
        if($this->hasEventHandler(static::EVENT_AFTER_SUBMIT))
            $this->onAfterSubmit(new ProjectSubmitEvent($this));
    }

    /**
     * 监听事件
     * @param $event
     * @throws \Exception
     */
    protected function onAfterSubmit($event)
    {
        $this->raiseEvent(static::EVENT_AFTER_SUBMIT, $event);
    }

    /**
     * 生成合同
     * @return Contract
     * @throws \Exception
     */
    public function createContract()
    {
        // TODO: implement
        return Contract::create($this);
    }

    /**
     * 设置不可驳回
     * @throws \Exception
     */
    public function setAndSaveCannotBack()
    {
        // TODO: implement
        if(!$this->isCanBack())
            return;
        $this->is_can_back=0;
        $this->getProjectRepository()->saveCannotBack($this);
    }

    /**
     * 是否可以驳回
     * @return bool
     */
    public function isCanBack()
    {
        return $this->is_can_back==1;
    }


}