<?php
/**
 * Created by youyi000.
 * DateTime: 2018/4/11 17:17
 * Describe：
 */

namespace ddd\domain\entity\contract;


class BuyContract extends Contract
{
    public function init()
    {
        $this->type=ContractType::BUY_CONTRACT;
        parent::init(); // TODO: Change the autogenerated stub
    }


}