<?php
/**
 * Created by youyi000.
 * DateTime: 2018/4/17 11:16
 * Describe：
 */

namespace ddd\domain\entity\contract;


use ddd\Common\Domain\BaseValue;
use ddd\Common\Domain\IValue;

class ContractPayPlan extends BaseValue
{
    #region property

    /**
     * 标识
     * @var   int
     */
    public $plan_id;

    /**
     * 期数
     * @var   int
     */
    public $period;

    /**
     * 币种
     * @var   int
     */
    public $currency;

    /**
     * 金额
     * @var   int
     */
    public $amount;

    /**
     * 人民币金额
     * @var   int
     */
    public $amount_cny;

    /**
     * 计划付款日期
     * @var   int
     */
    public $plan_pay_date;

    /**
     * 帐期
     * @var   int
     */
    public $credit_period;

    /**
     * 费用类型
     * @var   int
     */
    public $expense_type;

    /**
     * 费用类型名称
     * @var   string
     */
    public $expense_name;

    /**
     * 是否预付
     * @var   boolean
     */
    public $is_advance;

    /**
     * 支付比例
     * @var   float
     */
    public $rate;

    #endregion

    public function equals(IValue $value)
    {
        // TODO: Change the autogenerated stub
        return $this->amount==$value->amount
                && $this->plan_pay_date==$value->plan_pay_date
                && $this->currency==$value->currency
                && $this->expense_type==$value->expense_type;
    }


}