<?php
/**
 * Created by youyi000.
 * DateTime: 2018/3/9 16:07
 * Describe：
 */

namespace ddd\domain\event\contract;


class ContractBusinessRejectEvent extends ContractRejectEvent
{
    function initEventName()
    {
        parent::initEventName(); // TODO: Change the autogenerated stub
        $this->eventName = '合同业务审核驳回';
    }
}