<?php
/**
 * Created by youyi000.
 * DateTime: 2018/4/19 16:27
 * Describe：
 */

namespace ddd\domain\event\contract;


use ddd\Common\Domain\BaseEvent;

class FileUploadedEvent extends BaseEvent
{
    public function initEventName()
    {
        parent::initEventName(); // TODO: Change the autogenerated stub

    }

}