<?php

/**
 * Created by vector.
 * DateTime: 2018/04/08 15:50
 * Describe：
 */
class ContractSettlementSubjectDetail extends BaseActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 't_contract_settlement_subject_detail';
    }

    public function relations() {
        return array(
            "otherAttachments" =>array(self::HAS_MANY, "ContractSettlementAttachment", array("base_id" => "detail_id"), "on" => "otherAttachments.status=1"),
        );
    }


    public function beforeSave()
    {
        if ($this->isNewRecord)
        {
            if (empty($this->create_time))
                $this->create_time = new CDbExpression("now()");
            if (empty($this->create_user_id))
                $this->create_user_id= Utility::getNowUserId();
        }
        if ($this->update_time == $this->getOldAttribute("update_time"))
        {
            $this->update_time = new CDbExpression("now()");
            $this->update_user_id = Utility::getNowUserId();
        }

        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }

}