<?php
/**
 * Created by vector.
 * DateTime: 2018/3/28 18:45
 * Describe：合同结算单商品结算明细（第二单位）
 */

class ContractSettlementGoodsSub extends BaseHasSubActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 't_contract_settlement_goods_sub';
    }


    public function beforeSave()
    {
        if ($this->update_time == $this->getOldAttribute("update_time"))
        {
            $this->update_time = new CDbExpression("now()");
            $this->update_user_id = Utility::getNowUserId();
        }

        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }
}