<?php
/**
 * Created by vector.
 * DateTime: 2018/3/27 11:35
 * Describe：合同结算项计算明细
 */

class ContractSettlementGoodsDetail extends BaseActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 't_contract_settlement_goods_detail';
    }

    public function relations()
    {
        return array(
            "goodsItems" => array(self::HAS_MANY, "ContractSettlementGoodsDetailItem", array("detail_id"=>"detail_id")),
        );
    }

    public function beforeSave()
    {
        if ($this->isNewRecord)
        {
            if (empty($this->create_time))
                $this->create_time = new CDbExpression("now()");
            if (empty($this->create_user_id))
                $this->create_user_id= Utility::getNowUserId();
        }
        if ($this->update_time == $this->getOldAttribute("update_time"))
        {
            $this->update_time = new CDbExpression("now()");
            $this->update_user_id = Utility::getNowUserId();
        }

        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }

}