<?php

/**
 * Created by vector.
 * DateTime: 2017/08/31 18:30
 * Describe：
 */
class ContractGoodsTarget extends BaseActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 't_contract_goods_target';
    }

    public function relations()
    {
        return array(
            "lockPriceDetail" => array(self::HAS_MANY, "LockPriceDetail", "target_id"),//锁价明细
        );
    }

    public function beforeSave()
    {
        if ($this->isNewRecord)
        {
            if (empty($this->create_time))
                $this->create_time = new CDbExpression("now()");
            if (empty($this->create_user_id))
                $this->create_user_id= Utility::getNowUserId();
        }
        if ($this->update_time == $this->getOldAttribute("update_time"))
        {
            $this->update_time = new CDbExpression("now()");
            $this->update_user_id = Utility::getNowUserId();
        }
        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }

}