<?php
/**
 * Created by wwb.
 * DateTime: 2017/10/11 11:47
 * Describe：
 */

class ContractOverdue extends BaseHasSubActiveRecord
{
    const STATUS_NORMAL = 0;//正常
    const STATUS_DUE = -1;//催收


    const HAS_OVERDUE = 1;//有逾期
    const NO_OVERDUE = 0;//没有逾期

    const EXPENSE_TYPE_ONE = 1;//履约保证金
    const EXPENSE_TYPE_TWO = 2;//预付款
    const EXPENSE_TYPE_Three  = 3;//货款
    const EXPENSE_TYPE_FOUR = 4;//进口关税增值税保证金
    const EXPENSE_TYPE_FIVE = 5;//其他

    const SUBJECT_TYPE_ONE = 1;//货款
    const SUBJECT_TYPE_TWO = 2;//保理费
    const SUBJECT_TYPE_THREE = 3;//服务费
    const SUBJECT_TYPE_FOUR = 4;//运费
    const SUBJECT_TYPE_FIVE = 5;//仓储费
    const SUBJECT_TYPE_SIX = 6; //税款保证金
    const SUBJECT_TYPE_SEVEN = 7;//履约保证金
    const SUBJECT_TYPE_EIGHT = 8;//预付款
    

    const MONTH_DAY = 30;//一个月30天
    const AMOUNT_OVERDUE_PERCENT = 80;// 金额逾期百分比，80%

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 't_contract_overdue';//表名
    }

    public function relations()
    {
        return array(
            
        );
    }

    public function beforeSave()
    {
        if ($this->isNewRecord)
        {
            if (empty($this->create_time))
                $this->create_time = new CDbExpression("now()");
            /*if (empty($this->create_user_id))
                $this->create_user_id= Utility::getNowUserId();*/
        }
        if ($this->update_time == $this->getOldAttribute("update_time"))
        {
            $this->update_time = new CDbExpression("now()");
            //$this->update_user_id = Utility::getNowUserId();
        }
        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }
}