<?php
/**
 * Created by youyi000.
 * DateTime: 2017/9/5 14:43
 * Describe：
 */

class ContractFile extends BaseActiveRecord
{
    const STATUS_BACK = -2; //合同审核驳回
    const STATUS_DELETED = -1; //已删除
    const STATUS_NOT_UPLOAD = 0;  //合同未上传
    const STATUS_NOT_SUBMIT = 1; //合同未提交
    const STATUS_CHECKING = 3; //合同审核中(已提交)
    const STATUS_CHECK_PASS = 6; //合同审核通过

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 't_contract_file';
    }

    public function relations() {
        return array(
            "project" => array(self::BELONGS_TO, "Project", "project_id"),//项目信息
            "contract" => array(self::BELONGS_TO, "Contract", "contract_id"),

        );
    }

    protected function afterDelete()
    {
        parent::afterDelete(); // TODO: Change the autogenerated stub
        try
        {
            if(file_exists($this->file_path)) {
                unlink($this->file_path);
            }
        } catch (Exception $e) {  }
    }

    public function beforeSave()
    {
        if ($this->isNewRecord)
        {
            if (empty($this->create_time))
                $this->create_time = new CDbExpression("now()");
            if (empty($this->create_user_id))
                $this->create_user_id= Utility::getNowUserId();
        }
        if ($this->update_time == $this->getOldAttribute("update_time"))
        {
            $this->update_time = new CDbExpression("now()");
            $this->update_user_id = Utility::getNowUserId();
        }
        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }
}