<?php

/**
 * Created by vector.
 * DateTime: 2017/10/20 18:30
 * Describe：
 */
class CrossContractRelation extends BaseActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 't_cross_contract_relation';
    }

    public function relations()
    {
        return array(
            "contractGoods" => array(self::BELONGS_TO, "ContractGoods", "detail_id"),//交易明细
            "goods" => array(self::BELONGS_TO, "Goods", "goods_id"),//品名
            "contract" => array(self::BELONGS_TO, "Contract", "contract_id"),//合同
        );
    }

    public function beforeSave()
    {
        if ($this->isNewRecord)
        {
            if (empty($this->create_time))
                $this->create_time = new CDbExpression("now()");
            if (empty($this->create_user_id))
                $this->create_user_id= Utility::getNowUserId();
        }
        if ($this->update_time == $this->getOldAttribute("update_time"))
        {
            $this->update_time = new CDbExpression("now()");
            $this->update_user_id = Utility::getNowUserId();
        }
        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }

}