<?php

/**
 * Created by vector.
 * DateTime: 2017/10/17 18:30
 * Describe：
 */
class CrossOrder extends BaseActiveRecord
{

    const STATUS_BACK = -1; //调货单驳回
    const STATUS_SAVED = 1; //调货单保存
    const STATUS_CHECKING = 2; //调货单审核中
    const STATUS_PASS = 3; //调货单审核通过
    const STATUS_DONE = 4; //调货单借货完成

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 't_cross_order';
    }

    public function relations()
    {
        return array(
            "contractGoods" => array(self::HAS_ONE, "ContractGoods", array('contract_id'=>'contract_id', 'goods_id'=>'goods_id')),//交易明细
            "goods" => array(self::BELONGS_TO, "Goods", "goods_id"),//品名
            "contract" => array(self::BELONGS_TO, "Contract", "contract_id"),//合同
            "crossDetail" => array(self::HAS_MANY, "CrossDetail", "cross_id"),//借货明细信息
            //"borrowDetail" => array(self::BELONGS_TO, "CrossDetail", "detail_id"),//借货明细信息
            "project"=>array(self::BELONGS_TO, "Project", "project_id"),//项目
            "borrowCross"=>array(self::HAS_MANY, "CrossOrder", "relation_cross_id"),
            "crossContractDetail"=>array(self::HAS_MANY, "CrossContractDetail", 'cross_id'),
            "borrowContractDetail"=>array(self::BELONGS_TO, "CrossContractDetail", 'detail_id'),
        );
    }

    public function beforeSave()
    {
        if ($this->isNewRecord)
        {
            if (empty($this->create_time))
                $this->create_time = new CDbExpression("now()");
            if (empty($this->create_user_id))
                $this->create_user_id= Utility::getNowUserId();
        }
        if ($this->update_time == $this->getOldAttribute("update_time"))
        {
            $this->update_time = new CDbExpression("now()");
            $this->update_user_id = Utility::getNowUserId();
        }
        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }

}