<?php

/**
 * Created by vector.
 * DateTime: 2017/10/17 18:30
 * Describe：
 */
class CrossDetail extends BaseActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 't_cross_detail';
    }

    public function relations()
    {
        return array(
            "contractGoods" => array(self::BELONGS_TO, "ContractGoods", "detail_id"),//交易明细
            "goods" => array(self::BELONGS_TO, "Goods", "goods_id"),//品名
            "contract" => array(self::BELONGS_TO, "Contract", "contract_id"),//合同
            "stock" => array(self::BELONGS_TO, "Stock", "stock_id"),//库存
            "stockDeliveryDetail"=>array(self::HAS_MANY, "StockDeliveryDetail", "cross_detail_id"),//出货单明细
            "stockOutDetail"=>array(self::HAS_MANY, "StockOutDetail", "cross_detail_id"),//出库单明细
            "crossOrder"=>array(self::BELONGS_TO, "CrossOrder", "cross_id"),//调货单
        );
    }

    public function beforeSave()
    {
        if ($this->isNewRecord)
        {
            if (empty($this->create_time))
                $this->create_time = new CDbExpression("now()");
            if (empty($this->create_user_id))
                $this->create_user_id= Utility::getNowUserId();
        }
        if ($this->update_time == $this->getOldAttribute("update_time"))
        {
            $this->update_time = new CDbExpression("now()");
            $this->update_user_id = Utility::getNowUserId();
        }
        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }

}