<?php
/**
 * Created by vector.
 * DateTime: 2018/4/2 10:26
 * Describe：发货单结算单
 */

class DeliverySettlement extends BaseActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 't_delivery_settlement';
    }

    public function relations() {
        return array(
            "contractSettlementGoods"=>array(self::HAS_MANY, "ContractSettlementGoods", array('settle_id'=>'settle_id', 'contract_id'=>'contract_id')),
            "orders"=>array(self::HAS_MANY, "DeliverySettlementDetail", array('settle_id'=>'settle_id')),
            "saleContract"=>array(self::HAS_ONE, "ContractSettlement", array('contract_id'=>'contract_id')),
            "deliveryOrder"=>array(self::HAS_ONE, "DeliveryOrder", array('order_id'=>'order_id')),
        );
    }

    public function beforeSave()
    {
        if ($this->isNewRecord)
        {
            if (empty($this->create_time))
                $this->create_time = new CDbExpression("now()");
            if (empty($this->create_user_id))
                $this->create_user_id= Utility::getNowUserId();
        }
        if ($this->update_time == $this->getOldAttribute("update_time"))
        {
            $this->update_time = new CDbExpression("now()");
            $this->update_user_id = Utility::getNowUserId();
        }

        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }
}