<?php
/**
 * Created by vector.
 * DateTime: 2018/3/27 16:29
 * Describe：提单结算单
 */

class LadingSettlement extends BaseActiveRecord
{
    const STATUS_STOP   = -9;//结算作废
    const STATUS_RECALL = -2;//结算撤回
    const STATUS_BACK   = -1;//结算审核驳回
    const STATUS_NEW 	= 0; //结算新创建
    const STATUS_TEMP_SAVE = 1;//结算已暂存
    const STATUS_SAVED  = 2; //结算已保存


    const STATUS_SUBMIT = 10; //结算已提交
    const STATUS_PASS   = 20; //结算审核通过

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 't_lading_settlement';
    }

    public function relations() {
        return array(
            "contractSettlementGoods"=>array(self::HAS_MANY, "ContractSettlementGoods", array('settle_id'=>'settle_id','contract_id'=>'contract_id')),
            "ladings"=>array(self::HAS_MANY, "StockBatchSettlement", array('settle_id'=>'settle_id')),
            "stockBatch"=>array(self::HAS_ONE, "StockNotice", array('batch_id'=>'lading_id')),
            //"buyContract"=>array(self::HAS_ONE, "ContractSettlement", array('contract_id'=>'contract_id')),
        );
    }

    public function beforeSave()
    {
        if ($this->isNewRecord)
        {
            if (empty($this->create_time))
                $this->create_time = new CDbExpression("now()");
            if (empty($this->create_user_id))
                $this->create_user_id= Utility::getNowUserId();
        }
        if ($this->update_time == $this->getOldAttribute("update_time"))
        {
            $this->update_time = new CDbExpression("now()");
            $this->update_user_id = Utility::getNowUserId();
        }

        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }
}