<?php

/**
 * Created by vector.
 * DateTime: 2017/08/31 18:30
 * Describe：
 */
class LockPriceDetail extends BaseActiveRecord
{
    const STATUS_TRASH = -9;//锁价作废
    const STATUS_SAVED = 1; //锁价保存


    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 't_lock_price_detail';
    }

    public function relations()
    {
        return array(
            "target" => array(self::BELONGS_TO, "ContractGoodsTarget", "target_id"),//计价标的
            "goods" => array(self::BELONGS_TO, "Goods", "goods_id"),//商品信息
        );
    }

    public function beforeSave()
    {
        if ($this->isNewRecord)
        {
            if (empty($this->create_time))
                $this->create_time = new CDbExpression("now()");
            if (empty($this->create_user_id))
                $this->create_user_id= Utility::getNowUserId();
        }
        if ($this->update_time == $this->getOldAttribute("update_time"))
        {
            $this->update_time = new CDbExpression("now()");
            $this->update_user_id = Utility::getNowUserId();
        }
        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }

}