<?php
/**
 * Created by youyi000.
 * DateTime: 2017/10/23 11:05
 * Describe：
 */

class PayApplication extends BaseBusinessActiveRecord
{

    const CATEGORY_NORMAL=1;//正常付款
    const CATEGORY_CLAIMING=2;//后认领付款

    const TYPE_CONTRACT=11;//单合同付款
    const TYPE_SELL_CONTRACT=12;//销售合同付款
    const TYPE_MULTI_CONTRACT=13;//多合同付款
    const TYPE_PROJECT=14;//项目下付款
    const TYPE_CORPORATION=15;//交易主体下的付款
    const TYPE_CLAIM=20;//待认领付款


    const STATUS_NOT_SAVE = -5; //未保存
    const STATUS_TRASHED=-10;//已作废
    const STATUS_WITHDRAW = -20;//已撤回
    const STATUS_NEW=0;
    const STATUS_BACK=1;//驳回
    const STATUS_SUBMIT=10;//已提交

    const STATUS_IN_AUTO_PAYMENT=20;//自动实付中

//    const STATUS_AUTO_PAYMENT_FAILED = 25; //自动实付失败

    const STATUS_CHECKED=30;//已审核通过

    const STATUS_IN_MANUAL_PAYMENT=32;//手动实付中

    // const STATUS_STOP_CHECKING=34;//止付审核中
    const STATUS_STOP=35;//已止付

    const STATUS_PAID=40;//已完成付款



    const STATUS_DONE=99;//已付款完成


    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function setId()
    {
        $this->apply_id=IDService::getPayApplicationId();
    }

    public function tableName()
    {
        return "t_pay_application";
    }

    public function relations()
    {
        return array(
            "project" => array(self::BELONGS_TO, "Project", "project_id"),//项目信息
            "contract" => array(self::BELONGS_TO, "Contract", "contract_id"),
            "corporation" => array(self::BELONGS_TO, "Corporation", "corporation_id"),
            "details" => array(self::HAS_MANY, "PayApplicationDetail", "apply_id"),
            "subject" => array(self::BELONGS_TO, "Subject", "subject_id"),
            "extra" => array(self::HAS_ONE, "PayApplicationExtra", "apply_id"),
            "factor" => array(self::HAS_ONE, "Factor", "apply_id"),
            "creator"=>array(self::BELONGS_TO, "SystemUser",array('create_user_id'=>'user_id')), // 创建人
        );
    }


    /*public function __set($name, $value)
    {
        if($name=="remark")
        {
            if(empty($this->extra))
            {
                $this->extra=new PayApplicationExtra();
            }
            $this->sub["remark"]=$value;
        }
        else
            parent::__set($name, $value); // TODO: Change the autogenerated stub
    }

    public function __get($name)
    {
        if($name=="remark" && !empty($this->extra))
        {
            return $this->sub["remark"];
        }
        return parent::__get($name); // TODO: Change the autogenerated stub
    }*/


    /**
     * 是否可以修改
     * @param null $status
     * @return bool
     */
    public function isCanEdit($status=null)
    {
        if($status==null)
            $status=$this->status;
        return ($status<PayApplication::STATUS_SUBMIT && $status>=PayApplication::STATUS_NEW || $status == PayApplication::STATUS_WITHDRAW || $status == self::STATUS_NOT_SAVE);
    }

    /**
     * 是否可以作废
     * @param null $status
     * @return bool
     */
    public function isCanTrash($status=null)
    {
        if($status==null)
            $status=$this->status;

        return ($status<self::STATUS_SUBMIT && $status != self::STATUS_TRASHED);
    }

    /**
     * 是否可以认领
     * @param null $status
     * @return bool
     */
    public function isCanClaim($status=null)
    {
        if($status==null)
            $status=$this->status;
        return ($status>=self::STATUS_CHECKED && $status<self::STATUS_DONE && bccomp($this->amount_paid, 0, 2) === 1 && bccomp($this->amount_paid, $this->amount_claim, 2) === 1);
    }

}