<?php
class ProjectCreditDetail extends BaseActiveRecord
{
    const STATUS_DELETE = -1; // 业务审核驳回之后,额度占用数据全部废弃

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return "t_project_credit_detail";
    }

    public function relations()
    {
        return array(
            "quotaPartner" => array(self::BELONGS_TO, "Partner", "corporation_id"),//项目信息
            "quotaManager" => array(self::BELONGS_TO, "SystemUser", "to_user_id"),
        );
    }

    public function beforeSave()
    {
        if ($this->isNewRecord)
        {
            if (empty($this->create_time))
                $this->create_time = new CDbExpression("now()");
            if (empty($this->create_user_id))
                $this->create_user_id= Utility::getNowUserId();
        }
        if ($this->update_time == $this->getOldAttribute("update_time"))
        {
            $this->update_time = new CDbExpression("now()");
            $this->update_user_id = Utility::getNowUserId();
        }
        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }
}