<?php

/**
 * Created by youyi000.
 * DateTime: 2016/6/27 16:37
 * Describe：
 */
class ProjectAttachment extends BaseActiveRecord
{
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName() {
        return 't_project_attachment';
    }

    protected function afterDelete()
    {
        parent::afterDelete(); // TODO: Change the autogenerated stub

        try
        {
            if (file_exists($this->file_path)) {
                unlink($this->file_path);
            }
        } catch (Exception $e) {  }
    }


    /**
     * 删除成功返回1，否则返回错误信息或0
     * @return int|string
     */
    public static function del($id)
    {
        if (empty($id))
        {
            return "id不能为空！";
        }

        $obj = ProjectAttachment::model()->findByPk($id);
        if (empty($obj->id))
        {
            return "信息不存在";
        }
        $res=$obj->delete();
        if ($res)
        {
            return 1;
        } else {
            return "操作失败！";
        }
    }


}
