<?php

/**
 * Created by youyi000.
 * DateTime: 2017/4/11 11:14
 * Describe：
 */
class ProjectCredit extends BaseActiveRecord
{

    const STATUS_NEW=0;//新项目
    const STATUS_SUBMIT=2;//额度占用申请中
    const STATUS_CONFIRM=6;//已确认

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return "t_project_credit";
    }

    public function beforeSave()
    {
        if ($this->isNewRecord)
        {
            if (empty($this->create_time))
                $this->create_time = new CDbExpression("now()");
            if (empty($this->create_user_id))
                $this->create_user_id= Utility::getNowUserId();
        }
        if ($this->update_time == $this->getOldAttribute("update_time"))
        {
            $this->update_time = new CDbExpression("now()");
            $this->update_user_id = Utility::getNowUserId();
        }
        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }

}