<?php

/**
 * 收款流水认领
 */
class ReceiveConfirm extends BaseActiveRecord
{

    const STATUS_ABORTED=-1;//作废
    const STATUS_NEW=0;//新建
    const STATUS_SUBMITED=1;//已提交

    const STATUS_DONE=2; // 认领完成

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 't_receive_confirm';
    }

    public function relations()
    {
        return array(
            "flow" => array(self::BELONGS_TO, "BankFlow", "flow_id"),
            "contract" => array(self::BELONGS_TO, "Contract", "contract_id"),
            "creator" => array(self::BELONGS_TO, "SystemUser", "create_user_id"),
            "project" => array(self::BELONGS_TO, "Project", "project_id"),
            "receiveDetail" => array(self::HAS_MANY, "ReceiveDetail", "receive_id"),
            "finSubject" => array(self::BELONGS_TO, "Subject", array("subject" => "subject_id")),
        );
    }

    public function beforeSave() {
        if ($this->isNewRecord) {
            if (empty($this->create_time)) {
                $this->create_time = new CDbExpression("now()");
            }
            if (empty($this->create_user_id)) {
                $this->create_user_id = Utility::getNowUserId();
            }
        }
        if ($this->update_time == $this->getOldAttribute("update_time")) {
            $this->update_time = new CDbExpression("now()");
            $this->update_user_id = Utility::getNowUserId();
        }

        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }


}