<?php
class StockBatchSettlement extends BaseHasSubActiveRecord
{

    const STATUS_BACK = -1;//审核驳回
    const STATUS_NEW = 0;//新增加
    const STATUS_SUBMIT = 10;//提交(待审核)
    const STATUS_PASS = 20;//审核通过

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 't_stock_batch_settlement';
    }

    public function relations() {
        return array(
            "sub" => array(self::HAS_ONE, "StockBatchSettlementSub", "item_id"),
            "goods" => array(self::BELONGS_TO, "Goods", "goods_id"),
            "stockBatch" => array(self::BELONGS_TO, "StockNotice", "batch_id"),
            "contract" => array(self::BELONGS_TO, "Contract", "contract_id"),
        );
    }

    public function beforeSave()
    {
        if ($this->isNewRecord)
        {
            if (empty($this->create_time))
                $this->create_time = new CDbExpression("now()");
            if (empty($this->create_user_id))
                $this->create_user_id= Utility::getNowUserId();
        }
        if ($this->update_time == $this->getOldAttribute("update_time"))
        {
            $this->update_time = new CDbExpression("now()");
            $this->update_user_id = Utility::getNowUserId();
        }
        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }

    protected function beforeDelete()
    {

        foreach ($this->details as $model)
        {
            $res=$model->delete();
            if(!$res)
                return false;
        }

        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }


}