<?php
class StockBatchSettlementSub extends BaseActiveRecord
{


    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 't_stock_batch_settlement_sub';
    }

    public function beforeSave()
    {
        if ($this->isNewRecord)
        {
        }
        if ($this->update_time == $this->getOldAttribute("update_time"))
        {
            $this->update_time = new CDbExpression("now()");
            $this->update_user_id = Utility::getNowUserId();
        }
        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }

    protected function beforeDelete()
    {

        foreach ($this->details as $model)
        {
            $res=$model->delete();
            if(!$res)
                return false;
        }

        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }


}