<?php
/**
 * Created by youyi000.
 * DateTime: 2017/10/11 11:47
 * Describe：
 */

class Stock extends BaseHasSubActiveRecord
{


    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 't_stock';
    }

    public function relations()
    {
        return array(
            "project" => array(self::BELONGS_TO, "Project", "project_id"),//项目信息
            "contract" => array(self::BELONGS_TO, "Contract", "contract_id"),
            "sub" => array(self::HAS_ONE, "StockSub", "stock_id"),
            "store" => array(self::BELONGS_TO, "Storehouse", "store_id"),
            "stockIn" => array(self::BELONGS_TO, "StockIn", "stock_in_id"),
        );
    }

    public function beforeSave()
    {
        if ($this->isNewRecord)
        {
            if (empty($this->create_time))
                $this->create_time = new CDbExpression("now()");
            if (empty($this->create_user_id))
                $this->create_user_id= Utility::getNowUserId();
        }
        if ($this->update_time == $this->getOldAttribute("update_time"))
        {
            $this->update_time = new CDbExpression("now()");
            $this->update_user_id = Utility::getNowUserId();
        }
        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }
}